### ISSUE TITLE
Checkpoint 1 

### ISSUE THREAD

**Issue by Ricardo-P** [Ricardo-P/IndieProject#1]
@pawaitemadisoncollege My Checkpoint 1 is ready to be reviewed.

**Comment by pawaitemadisoncollege** [comment]
Hi @Ricardo-P ! 

Thanks for sharing your indie project checkpoint 1! You are off to a good start with a fun and useful project idea.

Following are my observations and notes about how this should be improved:

**Problem statement**

Does a good job laying out the problem and explaining how your application solves it.

- [ ] Technology list - did we talk about a service/api to use? 
- [ ] Remember to update the technology list as you add libraries and tech to your project.

**User stories**

Your MVP user stories feel like they are right-sized for the semester. 

A few things:

- [ ] Should have a sign out user story too.
- [ ] Full CRUD is a requirement of the project, but I don't see a delete scenario here. Is there a delete story that would make sense for your project?  
- [ ] I'm looking for a user story that might involve a web service - have you identified anything for this yet?
- [ ] Instead of storing this information in a word document which requires a download to view, use a markdown document so that it is easy to view in directly Github. 

**Project plan**

This is a start!

- [ ] Instead of storing this information in a word document which requires a download to view, use a markdown document so that it is easy to view in directly Github. 
- [ ] I recommend adding more detail to your plan. Start by layout out each user story and adding your target dates for working on and completing that story. Then, lay out the tasks needed to complete the story. Add Checkpoints 2 and 3 and the tasks you need to complete to achieve those, including the dates when you will do them. Refer to the Fat Bike Trail Reports demo project for an example of the level of detail that can help you identify all the work that needs to be completed to meet you goal. 

**Screen design**

There are currently three screens: log in, sign up, and the home page. 

- [ ] I recommend switching the `log in` link/button to `log out` if the user is already logged in. 
- [ ] When comparing user stories to screens, I didn't see screens for the stories related to selecting ingratiates, filtering recipes by dietary restrictions, viewing recipe details, and saving favorites. All MVP user stories should be represented in your design.

**Reflection statements/Time Log**

This should represent all time spend working on this course. 

- [ ] You currently only have one entry for 1/31/24. I'm guessing there is quite a lot missing here. 


**Other**

- [ ] Before adding any files that contain userids/passwords to your project, it would be a good idea to add them to .gitignore so that they don't end up in Github. I'd recommend ignoring any log files as well (easily accomplished by adding your logs directory to the .gitignore file). 

To reach a "MET" level for checkpoint one, please address the items listed above for screens, user stories, project plan, and time log. Reply to this issue when those items are added a ready for a second review. 

If you have any questions please ask!

**Comment by pawaitemadisoncollege** [comment]
@Ricardo-P Can you let me know how the updates above are coming along? Any questions?
